Hunting and Gathering = Caccia e raccolta
Chipped Stone Tools = Strumenti in pietra scheggiata
Fire Control = Controllo del fuoco
Language and Oral Traditions = Linguaggio e tradizioni orali
Organized Hunting = Caccia organizzata
Ancestor Rites = Riti degli antenati
Tribal Organization = Organizzazione tribale
Tribal Society = Società tribale
Sedentism = Sedentarizzazione
Megalithism = Megalitismo
Barter and Trade = Baratto e commercio
Coinage = Coniazione monetaria
Human Domestication (Cats) = Addomesticamento dell'uomo (gatti)
